from __future__ import annotations

import hashlib
import re
from collections import Counter, defaultdict
from pathlib import Path

from repo_intel.domain.models import RepositoryRecord, SddDocumentRecord, SemanticChunkRecord
from repo_intel.integrations.notebooklm.models import NotebookLmSourceBundle


def generate_notebooklm_bundles(
    workspace: Path,
    project_name: str,
    source_root: Path,
    repositories: list[RepositoryRecord],
    documents: list[SddDocumentRecord],
    chunks: list[SemanticChunkRecord],
    max_source_chars: int,
) -> list[NotebookLmSourceBundle]:
    source_root.mkdir(parents=True, exist_ok=True)
    for old_file in source_root.glob("*.md"):
        old_file.unlink()

    repo_by_id = {repo.id: repo for repo in repositories}
    docs_by_repo: dict[str, list[SddDocumentRecord]] = defaultdict(list)
    chunks_by_repo: dict[str, list[SemanticChunkRecord]] = defaultdict(list)
    for document in documents:
        docs_by_repo[document.repository_id].append(document)
    for chunk in chunks:
        chunks_by_repo[chunk.repository_id].append(chunk)

    generated: list[tuple[str, str, str]] = []
    generated.append(
        (
            f"{project_name} - 00 Project Brief",
            "00-project-brief.md",
            render_project_brief_source(workspace, project_name, repositories, documents, chunks),
        )
    )
    generated.append(
        (
            f"{project_name} - 01 Repository Map",
            "01-repository-map.md",
            render_repository_map(project_name, repositories, documents, chunks),
        )
    )
    generated.append(
        (
            f"{project_name} - 02 Architecture and Decisions",
            "02-architecture-and-decisions.md",
            render_architecture_decisions(project_name, repo_by_id, documents, chunks, max_source_chars),
        )
    )
    generated.append(
        (
            f"{project_name} - 03 Topic Map",
            "03-topic-map.md",
            render_topic_map(project_name, repo_by_id, chunks),
        )
    )

    for repo in repositories:
        repo_chunks = chunks_by_repo.get(repo.id, [])
        repo_docs = docs_by_repo.get(repo.id, [])
        content = render_repo_source(project_name, repo, repo_docs, repo_chunks, max_source_chars)
        generated.append((f"{project_name} - Repo - {repo.name}", f"repo-{slugify(repo.name)}.md", content))

    bundles: list[NotebookLmSourceBundle] = []
    for title, filename, content in generated:
        path = source_root / filename
        normalized = content.rstrip() + "\n"
        path.write_text(normalized, encoding="utf-8")
        bundles.append(
            NotebookLmSourceBundle(
                title=title,
                path=path,
                content_hash=hashlib.sha256(normalized.encode("utf-8")).hexdigest(),
            )
        )
    return bundles


def render_project_brief_source(
    workspace: Path,
    project_name: str,
    repositories: list[RepositoryRecord],
    documents: list[SddDocumentRecord],
    chunks: list[SemanticChunkRecord],
) -> str:
    brief_path = workspace / ".repo-intel" / "briefs" / "project-brief.md"
    lines = [
        f"# {project_name} NotebookLM Source: Project Brief",
        "",
        "Generated by repo-intel from indexed SDD/AI documentation.",
        "",
        "## Indexing Snapshot",
        "",
        f"- Repositories: {len(repositories)}",
        f"- SDD documents: {len(documents)}",
        f"- Semantic chunks: {len(chunks)}",
        "",
    ]
    if brief_path.exists():
        lines.extend(["## Project Brief", "", brief_path.read_text(encoding="utf-8", errors="ignore")])
    else:
        lines.extend(
            [
                "## Project Brief",
                "",
                "No project brief has been generated yet. Run `repo-intel brief <workspace>` for a richer overview.",
            ]
        )
    return "\n".join(lines)


def render_repository_map(
    project_name: str,
    repositories: list[RepositoryRecord],
    documents: list[SddDocumentRecord],
    chunks: list[SemanticChunkRecord],
) -> str:
    docs_by_repo = Counter(doc.repository_id for doc in documents)
    chunks_by_repo = Counter(chunk.repository_id for chunk in chunks)
    lines = [
        f"# {project_name} Repository Map",
        "",
        "This source helps NotebookLM understand the repository boundaries and documentation coverage.",
        "",
    ]
    for repo in repositories:
        lines.extend(
            [
                f"## {repo.name}",
                "",
                f"- Relative path: `{repo.relative_path or '.'}`",
                f"- Branch: `{repo.branch or 'unknown'}`",
                f"- Git status: `{repo.git_status}`",
                f"- SDD roots: {', '.join(repo.sdd_roots) or 'none detected'}",
                f"- Documents indexed: {docs_by_repo.get(repo.id, 0)}",
                f"- Semantic chunks indexed: {chunks_by_repo.get(repo.id, 0)}",
                "",
            ]
        )
    return "\n".join(lines)


def render_architecture_decisions(
    project_name: str,
    repo_by_id: dict[str, RepositoryRecord],
    documents: list[SddDocumentRecord],
    chunks: list[SemanticChunkRecord],
    max_source_chars: int,
) -> str:
    priority_types = {"architecture", "adr", "api-contract", "sdd-spec", "product", "roadmap"}
    priority_doc_ids = {doc.id for doc in documents if doc.doc_type in priority_types}
    selected = [chunk for chunk in chunks if chunk.document_id in priority_doc_ids]
    lines = [
        f"# {project_name} Architecture and Decisions",
        "",
        "This source groups architecture, ADR, contract, product, roadmap, and SDD spec sections.",
        "",
    ]
    lines.extend(render_chunk_sections(repo_by_id, selected, remaining_chars(lines, max_source_chars)))
    return "\n".join(lines)


def render_topic_map(
    project_name: str,
    repo_by_id: dict[str, RepositoryRecord],
    chunks: list[SemanticChunkRecord],
) -> str:
    topic_map: dict[str, set[str]] = defaultdict(set)
    for chunk in chunks:
        repo = repo_by_id.get(chunk.repository_id)
        if not repo:
            continue
        metadata = chunk.metadata
        candidates = [
            metadata.get("section", ""),
            metadata.get("doc_type", ""),
            metadata.get("path", ""),
            *metadata.get("tags", []),
        ]
        for candidate in candidates:
            for topic in extract_topics(str(candidate)):
                topic_map[topic].add(repo.name)

    lines = [
        f"# {project_name} Topic Map",
        "",
        "Deterministic topic map generated from SDD metadata, paths, headings, sections, and tags.",
        "",
    ]
    for topic, repos in sorted(topic_map.items(), key=lambda item: (-len(item[1]), item[0]))[:120]:
        lines.append(f"- **{topic}**: {', '.join(sorted(repos))}")
    return "\n".join(lines)


def render_repo_source(
    project_name: str,
    repo: RepositoryRecord,
    documents: list[SddDocumentRecord],
    chunks: list[SemanticChunkRecord],
    max_source_chars: int,
) -> str:
    lines = [
        f"# {project_name} Repository Source: {repo.name}",
        "",
        "This source contains indexed SDD/AI documentation sections for one repository.",
        "",
        "## Repository Metadata",
        "",
        f"- Relative path: `{repo.relative_path or '.'}`",
        f"- Branch: `{repo.branch or 'unknown'}`",
        f"- Git status: `{repo.git_status}`",
        "",
        "## Indexed Documents",
        "",
    ]
    for document in sorted(documents, key=lambda item: item.repo_relative_path):
        lines.append(f"- `{document.repo_relative_path}` ({document.doc_type}) - {document.title}")
    lines.extend(["", "## SDD Sections", ""])
    lines.extend(render_chunk_sections({repo.id: repo}, chunks, remaining_chars(lines, max_source_chars)))
    return "\n".join(lines)


def render_chunk_sections(
    repo_by_id: dict[str, RepositoryRecord],
    chunks: list[SemanticChunkRecord],
    max_source_chars: int,
) -> list[str]:
    lines: list[str] = []
    size = 0
    for chunk in sorted(chunks, key=chunk_sort_key):
        metadata = chunk.metadata
        repo = repo_by_id.get(chunk.repository_id)
        header = (
            f"### {repo.name if repo else metadata.get('repo', 'unknown')} / "
            f"{metadata.get('path', '')} / {metadata.get('section', '')}"
        )
        block = "\n".join(
            [
                header,
                "",
                f"- Doc type: `{metadata.get('doc_type', '')}`",
                f"- Branch: `{metadata.get('branch', '')}`",
                f"- Commit: `{metadata.get('last_modified_commit', '')}`",
                "",
                chunk.text.strip(),
                "",
            ]
        )
        if size + len(block) > max_source_chars:
            lines.extend(["", "_Source truncated by repo-intel max_source_chars._"])
            break
        lines.append(block)
        size += len(block)
    if not lines:
        lines.append("_No matching SDD sections found._")
    return lines


def chunk_sort_key(chunk: SemanticChunkRecord) -> tuple[str, str, str]:
    metadata = chunk.metadata
    return (
        str(metadata.get("repo", "")),
        str(metadata.get("path", "")),
        str(metadata.get("section", "")),
    )


def extract_topics(value: str) -> list[str]:
    cleaned = re.sub(r"[_./-]+", " ", value)
    words = [word for word in re.findall(r"[A-Za-z0-9ÁÉÍÓÚÜÑáéíóúüñ]+", cleaned) if len(word) >= 4]
    stop = {"docs", "documentation", "architecture", "readme", "index", "source", "section"}
    topics = []
    for word in words:
        normalized = word.strip()
        if normalized.lower() not in stop:
            topics.append(normalized[:1].upper() + normalized[1:])
    return topics


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug or "source"


def remaining_chars(lines: list[str], max_source_chars: int) -> int:
    used = len("\n".join(lines))
    return max(10000, max_source_chars - used)
